### ISSUE TITLE
BYOIP Sydney

### ISSUE THREAD

**Issue by sheepa** [ovh/infrastructure-roadmap#165] opened 2023-12-04 12:17 UTC
The BYOIP feature is missing from the Sydney datacenter.

Presumably this is being worked on but it would be nice to have a tracker for it so one can get notified when it's done.

**Comment by jslocinski** [comment] 2024-02-28 10:44
Yes, we're working on it, should be available in about 2 months.

**Comment by jslocinski** [comment] 2024-02-28 10:46
duplicate of https://github.com/ovh/infrastructure-roadmap/issues/168

**Closed as completed by jslocinski** 2024-02-28 10:46 UTC
Labels: BYOIP, IP
